version: 1
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
        command: |
          R -e 'devtools::install_deps(dependencies = TRUE)'
      - save_cache:
        key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
        paths:
          - "/usr/local/lib/R/site-library"
      - run:
        command: |
          R -e 'devtools::check()'
      - store_artifacts:
        path: man/
        destination: man
